In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# Path to CALCE data
calce_path = Path("../../data/raw/calce")

# List all battery folders
battery_folders = [f for f in calce_path.iterdir() if f.is_dir()]
print(f"Found {len(battery_folders)} battery folders:")
for f in battery_folders:
    print(f"  - {f.name}")

Found 4 battery folders:
  - CX2_16
  - CX2_33
  - CX2_34
  - CX2_36

In [4]:
# Pick the first battery
battery = battery_folders[0]
print(f"\nExploring: {battery.name}")
print(f"Number of files: {len(list(battery.glob('*')))}")

# Show first 20 file names
files = list(battery.glob("*.xlsx"))[:20]
for f in files:
    print(f"  - {f.name}")

Exploring: CX2_16
Number of files: 65
  - CX2_16_4_12_11.xlsx
  - CX2_16_6_20_11.xlsx
  - CX2_16_6_28_12.xlsx
  - CX2_16_6_30_11.xlsx
  - CX2_16_6_7_11.xlsx
  - CX2_16_7_03_12.xlsx
  - CX2_16_7_11_11.xlsx
  - CX2_16_7_12_12.xlsx
  - CX2_16_7_21_11.xlsx
  - CX2_16_7_23_12.xlsx
  - CX2_16_8_10_12.xlsx
  - CX2_16_8_19_11.xlsx
  - CX2_16_8_1_11.xlsx
  - CX2_16_8_20_12.xlsx
  - CX2_16_8_29_11.xlsx
  - CX2_16_8_30_12.xlsx
  - CX2_16_8_9_11.xlsx
  - CX2_16_9_10_12.xlsx
  - CX2_16_9_16_11.xlsx
  - CX2_16_9_20_11.xlsx

In [5]:
# Pick a normal-looking file (not self-discharge test)
test_file = battery / "CX2_16_1_30_12.xlsx"

print(f"\nExamining: {test_file.name}")

# Check sheet names
xl = pd.ExcelFile(test_file)
print(f"Sheet names: {xl.sheet_names}")

# Load first sheet
df = pd.read_excel(test_file, sheet_name=0)
print(f"\nShape: {df.shape}")
print(f"\nFirst 5 rows:")
df.head()

Examining: CX2_16_1_30_12.xlsx
Sheet names: ['Info', 'Channel_1-006', 'Statistics_1-006']

Shape: (4, 23)

First 5 rows:

,Unnamed: 0,Unnamed: 1,Unnamed: 2,TEST REPORT,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,NaN,1_12_12,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2012-01-30 00:00:00,NaN,NaN,NaN,Mapped_Aux_Number,NaN,NaN,...,NaN,NaN,NaN,Cell Grading,NaN,NaN,Concentration,Digital I/O,NaN,NaN
2,Channel,Start_DateTime,Schedule_File_Name,Creator,Comments,Chan_Num,Item_ID,Volt,Temp,Pres,...,Aux,SmartBty,Event,Grade,Internal_Resistance(Ohm),Discharge_Capacity(Ah),Concentration,Digital Input,Digital Output,Related Humidity
3,1-006,2012-01-12 15:53:38,CX2_point5C.sdu,NaN,NaN,16,NaN,0,0,0,...,False,False,False,NaN,NaN,NaN,0,0,0,NaN

In [6]:
# Check what's in the Info sheet
info_df = pd.read_excel(test_file, sheet_name='Info')
print("INFO SHEET:")
print(info_df)

INFO SHEET:
  Unnamed: 0           Unnamed: 1          Unnamed: 2          TEST REPORT  \
0        NaN                  NaN                 NaN              1_12_12
1        NaN                  NaN                 NaN  2012-01-30 00:00:00
2    Channel       Start_DateTime  Schedule_File_Name              Creator
3      1-006  2012-01-12 15:53:38     CX2_point5C.sdu                  NaN

  Unnamed: 4 Unnamed: 5 Unnamed: 6                  Unnamed: 7 Unnamed: 8  \
0        NaN        NaN        NaN                         NaN        NaN
1        NaN        NaN        NaN           Mapped_Aux_Number        NaN
2   Comments   Chan_Num    Item_ID                        Volt       Temp
3        NaN         16        NaN                           0          0

  Unnamed: 9  ... Unnamed: 13 Unnamed: 14 Unnamed: 15  \
0        NaN  ...         NaN         NaN         NaN
1        NaN  ...         NaN         NaN         NaN
2       Pres  ...         Aux    SmartBty       Event
3          0  ...       False       False       False

                                 Unnamed: 16               Unnamed: 17  \
0                                        NaN                       NaN
1                     Cell Grading                                 NaN
2                                      Grade  Internal_Resistance(Ohm)
3                                        NaN                       NaN

              Unnamed: 18    Unnamed: 19     Unnamed: 20     Unnamed: 21  \
0                     NaN            NaN             NaN             NaN
1                     NaN  Concentration     Digital I/O             NaN
2  Discharge_Capacity(Ah)  Concentration   Digital Input  Digital Output
3                     NaN              0               0               0

        Unnamed: 22
0               NaN
1               NaN
2  Related Humidity
3               NaN

[4 rows x 23 columns]

In [7]:
# Load the actual cycle data sheet (Channel_1-006)
cycle_df = pd.read_excel(test_file, sheet_name='Channel_1-006')

print(f"Shape: {cycle_df.shape}")
print(f"\nFirst 10 rows:")
cycle_df.head(10)

Shape: (17519, 17)

First 10 rows:

,Data_Point,Test_Time(s),Date_Time,Step_Time(s),Step_Index,Cycle_Index,Current(A),Voltage(V),Charge_Capacity(Ah),Discharge_Capacity(Ah),Charge_Energy(Wh),Discharge_Energy(Wh),dV/dt(V/s),Internal_Resistance(Ohm),Is_FC_Data,AC_Impedance(Ohm),ACI_Phase_Angle(Deg)
0,1,30.000283,2012-01-12 15:54:08,30.000284,1,1,0.000000,4.117773,0.000000,0.0,0.000000,0.0,0.000000,0.0,0,0,0
1,2,60.015499,2012-01-12 15:54:38,60.015500,1,1,0.000000,4.117773,0.000000,0.0,0.000000,0.0,0.000000,0.0,0,0,0
2,3,90.030861,2012-01-12 15:55:08,90.030861,1,1,0.000000,4.117773,0.000000,0.0,0.000000,0.0,0.000000,0.0,0,0,0
3,4,120.014716,2012-01-12 15:55:38,120.014716,1,1,0.000000,4.117773,0.000000,0.0,0.000000,0.0,0.000000,0.0,0,0,0
4,5,150.171587,2012-01-12 15:56:08,30.015424,3,1,0.000000,4.117935,0.000026,0.0,0.000108,0.0,0.000000,0.0,0,0,0
5,6,180.186846,2012-01-12 15:56:38,60.030683,3,1,0.000000,4.117773,0.000026,0.0,0.000108,0.0,0.000000,0.0,0,0,0
6,7,210.202117,2012-01-12 15:57:08,90.045954,3,1,0.000000,4.117773,0.000026,0.0,0.000108,0.0,0.000000,0.0,0,0,0
7,8,240.170310,2012-01-12 15:57:38,120.014147,3,1,0.000000,4.117935,0.000026,0.0,0.000108,0.0,0.000032,0.0,0,0,0
8,9,240.170762,2012-01-12 15:57:39,0.000003,4,1,0.720615,4.200065,0.000026,0.0,0.000108,0.0,0.000000,0.0,0,0,0
9,10,240.327257,2012-01-12 15:57:39,0.156497,4,1,0.669510,4.200065,0.000055,0.0,0.000233,0.0,0.000000,0.0,0,0,0

In [10]:
calce_path = Path("../../data/raw/calce")
battery_folders = [f for f in calce_path.iterdir() if f.is_dir()]

print("=" * 60)
print("CALCE DATASET OVERVIEW")
print("=" * 60)

for battery in battery_folders:
    print(f"\n📁 {battery.name}")
    
    # Count files
    all_files = list(battery.glob("*.xlsx"))
    print(f"   Total files: {len(all_files)}")
    
    # Separate regular vs special files
    regular = [f for f in all_files if 'self_discharge' not in f.name.lower()]
    special = [f for f in all_files if 'self_discharge' in f.name.lower()]
    
    print(f"   Regular cycle files: {len(regular)}")
    print(f"   Special test files: {len(special)}")
    
    # Check a sample file to understand structure
    if regular:
        sample = regular[0]
        xl = pd.ExcelFile(sample)
        print(f"   Sample file: {sample.name}")
        print(f"   Sheets: {xl.sheet_names}")

============================================================
CALCE DATASET OVERVIEW
============================================================

📁 CX2_16
   Total files: 52
   Regular cycle files: 52
   Special test files: 0
   Sample file: CX2_16_4_12_11.xlsx
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']

📁 CX2_33
   Total files: 45
   Regular cycle files: 45
   Special test files: 0
   Sample file: CX2_33_1_28_11.xlsx
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']

📁 CX2_34
   Total files: 43
   Regular cycle files: 43
   Special test files: 0
   Sample file: CX2_34_3_14_11.xlsx
   Sheets: ['Info', 'Channel_1-001', 'Statistics_1-001']

📁 CX2_36
   Total files: 48
   Regular cycle files: 48
   Special test files: 0
   Sample file: CX2_36_1_10_11.xlsx
   Sheets: ['Info', 'Channel_1-003', 'Statistics_1-003']

In [11]:
calce_path = Path("../../data/raw/calce")
battery_folders = [f for f in calce_path.iterdir() if f.is_dir()]

all_files_summary = []

for battery in battery_folders:
    print(f"\n{'='*60}")
    print(f"📁 {battery.name}")
    print(f"{'='*60}")
    
    excel_files = list(battery.glob("*.xlsx"))
    
    for file in excel_files:
        try:
            xl = pd.ExcelFile(file)
            sheets = xl.sheet_names
            
            # Get cycle data sheet name (the one with numbers)
            cycle_sheet = [s for s in sheets if 'Channel' in s][0]
            
            # Get number of rows in cycle data (without loading all data)
            df = pd.read_excel(file, sheet_name=cycle_sheet, nrows=0)
            num_columns = len(df.columns)
            
            # Get file size
            size_kb = file.stat().st_size / 1024
            
            # Try to get cycle range (min and max cycle index)
            cycle_data = pd.read_excel(file, sheet_name=cycle_sheet, usecols=['Cycle_Index'])
            min_cycle = cycle_data['Cycle_Index'].min()
            max_cycle = cycle_data['Cycle_Index'].max()
            num_cycles = len(cycle_data['Cycle_Index'].unique())
            
            all_files_summary.append({
                'battery': battery.name,
                'file': file.name,
                'sheets': ', '.join(sheets),
                'cycle_sheet': cycle_sheet,
                'rows': '?',
                'columns': num_columns,
                'size_kb': round(size_kb, 1),
                'min_cycle': min_cycle,
                'max_cycle': max_cycle,
                'num_cycles': num_cycles
            })
            
            print(f"\n📄 {file.name}")
            print(f"   Size: {size_kb:.1f} KB")
            print(f"   Sheets: {sheets}")
            print(f"   Cycle data sheet: {cycle_sheet}")
            print(f"   Columns: {num_columns}")
            print(f"   Cycle range: {min_cycle} to {max_cycle}")
            print(f"   Unique cycles: {num_cycles}")
            
        except Exception as e:
            print(f"\n❌ {file.name}: Error - {str(e)[:50]}")

# Create summary DataFrame
summary_df = pd.DataFrame(all_files_summary)
print(f"\n{'='*60}")
print("SUMMARY TABLE")
print(f"{'='*60}")
print(f"Total files analyzed: {len(summary_df)}")
print(f"\nFirst 10 files:")
summary_df.head(10)

============================================================
📁 CX2_16
============================================================

📄 CX2_16_4_12_11.xlsx
   Size: 3670.2 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_6_20_11.xlsx
   Size: 2521.7 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 36
   Unique cycles: 36

📄 CX2_16_6_28_12.xlsx
   Size: 449.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 9
   Unique cycles: 9

📄 CX2_16_6_30_11.xlsx
   Size: 3552.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_6_7_11.xlsx
   Size: 3090.6 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 34
   Unique cycles: 34

📄 CX2_16_7_03_12.xlsx
   Size: 2547.2 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_7_11_11.xlsx
   Size: 1234.0 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 14
   Unique cycles: 14

📄 CX2_16_7_12_12.xlsx
   Size: 2492.7 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_7_21_11.xlsx
   Size: 3540.2 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_7_23_12.xlsx
   Size: 2473.7 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_8_10_12.xlsx
   Size: 2458.8 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_8_19_11.xlsx
   Size: 3474.6 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_8_1_11.xlsx
   Size: 3552.0 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_8_20_12.xlsx
   Size: 2385.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_8_29_11.xlsx
   Size: 3432.6 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_8_30_12.xlsx
   Size: 2375.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_8_9_11.xlsx
   Size: 903.8 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 13
   Unique cycles: 13

📄 CX2_16_9_10_12.xlsx
   Size: 2294.7 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_9_16_11.xlsx
   Size: 3382.6 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_9_20_11.xlsx
   Size: 1534.9 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 23
   Unique cycles: 23

📄 CX2_16_9_6_11.xlsx
   Size: 247.8 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 4
   Unique cycles: 4

📄 CX2_16_10_14_11.xlsx
   Size: 3268.2 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_10_18_11.xlsx
   Size: 454.1 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 7
   Unique cycles: 7

📄 CX2_16_10_28_11.xlsx
   Size: 2530.1 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 41
   Unique cycles: 41

📄 CX2_16_10_4_11.xlsx
   Size: 3707.1 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_12_16_11.xlsx
   Size: 3110.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_1_30_12.xlsx
   Size: 2672.1 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_2_13_12_self discharge test.xlsx
   Size: 46.7 KB
   Sheets: ['Info', 'Channel_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 1
   Unique cycles: 1

📄 CX2_16_2_15_11.xlsx
   Size: 4161.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_2_25_11.xlsx
   Size: 3593.9 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 47
   Unique cycles: 47

📄 CX2_16_2_6_12.xlsx
   Size: 90.9 KB
   Sheets: ['Info', 'Channel_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 1
   Unique cycles: 1

📄 CX2_16_3_19_12.xlsx
   Size: 2649.7 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_3_21_11.xlsx
   Size: 3750.2 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_3_27_12.xlsx
   Size: 909.3 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 17
   Unique cycles: 17

📄 CX2_16_3_2_12.xlsx
   Size: 2664.3 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_3_7_11.xlsx
   Size: 3698.2 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_4_17_12.xlsx
   Size: 2664.6 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_4_18_11.xlsx
   Size: 865.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 12
   Unique cycles: 12

📄 CX2_16_4_1_11.xlsx
   Size: 3708.7 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_4_23_12.xlsx
   Size: 982.9 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 19
   Unique cycles: 19

📄 CX2_16_4_29_11.xlsx
   Size: 3607.1 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_4_5_12.xlsx
   Size: 2660.0 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_5_07_12.xlsx
   Size: 2603.8 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_5_13_11.xlsx
   Size: 1224.9 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 18
   Unique cycles: 18

📄 CX2_16_5_16_12.xlsx
   Size: 2630.2 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_5_22_12.xlsx
   Size: 2644.7 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_5_23_11.xlsx
   Size: 3517.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_5_9_11.xlsx
   Size: 3582.4 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_6_01_12.xlsx
   Size: 2587.0 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_16_6_10_11.xlsx
   Size: 496.5 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 6
   Unique cycles: 6

📄 CX2_16_6_13_11.xlsx
   Size: 1098.8 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 16
   Unique cycles: 16

📄 CX2_16_6_19_12.xlsx
   Size: 2554.9 KB
   Sheets: ['Info', 'Channel_1-006', 'Statistics_1-006']
   Cycle data sheet: Channel_1-006
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

============================================================
📁 CX2_33
============================================================

📄 CX2_33_1_28_11.xlsx
   Size: 1172.9 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 19
   Unique cycles: 19

📄 CX2_33_2_10_11.xlsx
   Size: 3009.5 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_2_21_11.xlsx
   Size: 2965.4 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_2_25_11.xlsx
   Size: 1138.5 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 20
   Unique cycles: 20

📄 CX2_33_3_17_11.xlsx
   Size: 2848.9 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_3_31_11.xlsx
   Size: 2815.5 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_3_7_11.xlsx
   Size: 2871.2 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_4_14_11.xlsx
   Size: 2776.1 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_4_18_11.xlsx
   Size: 393.8 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 7
   Unique cycles: 7

📄 CX2_33_4_26_11.xlsx
   Size: 2370.2 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 44
   Unique cycles: 44

📄 CX2_33_5_13_11.xlsx
   Size: 1097.7 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 21
   Unique cycles: 21

📄 CX2_33_5_20_11.xlsx
   Size: 2275.3 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 43
   Unique cycles: 43

📄 CX2_33_5_31_11.xlsx
   Size: 2621.7 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_5_5_11.xlsx
   Size: 2664.1 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_6_10_11.xlsx
   Size: 450.4 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 7
   Unique cycles: 7

📄 CX2_33_6_13_11.xlsx
   Size: 981.9 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 19
   Unique cycles: 19

📄 CX2_33_6_20_11.xlsx
   Size: 2198.1 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 42
   Unique cycles: 42

📄 CX2_33_6_30_11.xlsx
   Size: 2609.0 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_6_7_11.xlsx
   Size: 2740.7 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 40
   Unique cycles: 40

📄 CX2_33_7_11_11.xlsx
   Size: 1054.4 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 16
   Unique cycles: 16

📄 CX2_33_7_20_11.xlsx
   Size: 2558.7 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_8_17_11.xlsx
   Size: 2448.9 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_8_1_11.xlsx
   Size: 2556.4 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_8_9_11.xlsx
   Size: 773.3 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 16
   Unique cycles: 16

📄 CX2_33_9_13_11.xlsx
   Size: 1775.1 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 38
   Unique cycles: 38

📄 CX2_33_9_17_10.xlsx
   Size: 3513.0 KB
   Sheets: ['Info', 'Channel_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_9_20_11.xlsx
   Size: 1788.0 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 40
   Unique cycles: 40

📄 CX2_33_9_27_10.xlsx
   Size: 3521.6 KB
   Sheets: ['Info', 'Channel_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_9_6_11.xlsx
   Size: 217.8 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 5
   Unique cycles: 5

📄 CX2_33_9_7_10.xlsx
   Size: 1522.8 KB
   Sheets: ['Info', 'Channel_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 22
   Unique cycles: 22

📄 CX2_33_10_04_10.xlsx
   Size: 1557.5 KB
   Sheets: ['Info', 'Channel_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 23
   Unique cycles: 23

📄 CX2_33_10_05_10.xlsx
   Size: 417.9 KB
   Sheets: ['Info', 'Channel_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 7
   Unique cycles: 7

📄 CX2_33_10_14_11.xlsx
   Size: 2017.0 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_10_18_11.xlsx
   Size: 362.1 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 10
   Unique cycles: 10

📄 CX2_33_10_28_11.xlsx
   Size: 1742.0 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_10_4_11.xlsx
   Size: 2146.4 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_11_11_10.xlsx
   Size: 3376.2 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_11_22_10.xlsx
   Size: 3357.4 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_11_24_10.xlsx
   Size: 772.0 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 12
   Unique cycles: 12

📄 CX2_33_11_28_11.xlsx
   Size: 1703.7 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_12_16_11.xlsx
   Size: 1558.9 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_12_23_10.xlsx
   Size: 3250.0 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_12_8_10.xlsx
   Size: 3229.3 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_1_12_11.xlsx
   Size: 3180.5 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_33_1_24_11.xlsx
   Size: 3096.9 KB
   Sheets: ['Info', 'Channel_1-012', 'Statistics_1-012']
   Cycle data sheet: Channel_1-012
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

============================================================
📁 CX2_34
============================================================

📄 CX2_34_3_14_11.xlsx
   Size: 2013.1 KB
   Sheets: ['Info', 'Channel_1-001', 'Statistics_1-001']
   Cycle data sheet: Channel_1-001
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_34_3_21_11.xlsx
   Size: 1321.3 KB
   Sheets: ['Info', 'Channel_1-001', 'Statistics_1-001']
   Cycle data sheet: Channel_1-001
   Columns: 17
   Cycle range: 1 to 34
   Unique cycles: 34

📄 CX2_34_3_29_11.xlsx
   Size: 1899.9 KB
   Sheets: ['Info', 'Channel_1-001', 'Statistics_1-001']
   Cycle data sheet: Channel_1-001
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_34_3_7_11.xlsx
   Size: 2039.5 KB
   Sheets: ['Info', 'Channel_1-001', 'Statistics_1-001']
   Cycle data sheet: Channel_1-001
   Columns: 17
   Cycle range: 1 to 50
   Unique cycles: 50

📄 CX2_34_4_12_11.xlsx
   Size: 1912.2 KB
   Sheets: ['Info', 'Channel_1-001', 'Statistics_1-001']
   Cycle data sheet: Channel_1-001
   Columns: 17
   Cycle range: 1 to 50

,battery,file,sheets,cycle_sheet,rows,columns,size_kb,min_cycle,max_cycle,num_cycles
0,CX2_16,CX2_16_4_12_11.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,3670.2,1,50,50
1,CX2_16,CX2_16_6_20_11.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,2521.7,1,36,36
2,CX2_16,CX2_16_6_28_12.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,449.5,1,9,9
3,CX2_16,CX2_16_6_30_11.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,3552.5,1,50,50
4,CX2_16,CX2_16_6_7_11.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,3090.6,1,34,34
5,CX2_16,CX2_16_7_03_12.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,2547.2,1,50,50
6,CX2_16,CX2_16_7_11_11.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,1234.0,1,14,14
7,CX2_16,CX2_16_7_12_12.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,2492.7,1,50,50
8,CX2_16,CX2_16_7_21_11.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,3540.2,1,50,50
9,CX2_16,CX2_16_7_23_12.xlsx,"Info, Channel_1-006, Statistics_1-006",Channel_1-006,?,17,2473.7,1,50,50

In [12]:
calce_path = Path("../../data/raw/calce")
battery_path = calce_path / "CX2_16"

all_files = list(battery_path.glob("*.xlsx"))
all_cycles = []

for file in all_files:
    try:
        # Load cycle data
        xl = pd.ExcelFile(file)
        sheet = [s for s in xl.sheet_names if 'Channel' in s][0]
        df = pd.read_excel(file, sheet_name=sheet)
        
        # Add source file name as column
        df['source_file'] = file.name
        
        # Add battery ID
        df['battery_id'] = 'CX2_16'
        
        all_cycles.append(df)
        print(f"✅ Loaded {file.name}: {len(df)} rows")
    except Exception as e:
        print(f"❌ Failed: {file.name} - {e}")

# Combine all
if all_cycles:
    combined = pd.concat(all_cycles, ignore_index=True)
    print(f"\n{'='*60}")
    print(f"Total rows combined: {len(combined)}")
    print(f"Columns: {list(combined.columns)}")
    combined.head()
else:
    print("No files loaded")

✅ Loaded CX2_16_4_12_11.xlsx: 24195 rows
✅ Loaded CX2_16_6_20_11.xlsx: 16615 rows
✅ Loaded CX2_16_6_28_12.xlsx: 2849 rows
✅ Loaded CX2_16_6_30_11.xlsx: 23433 rows
✅ Loaded CX2_16_6_7_11.xlsx: 15780 rows
✅ Loaded CX2_16_7_03_12.xlsx: 16704 rows
✅ Loaded CX2_16_7_11_11.xlsx: 6227 rows
✅ Loaded CX2_16_7_12_12.xlsx: 16343 rows
✅ Loaded CX2_16_7_21_11.xlsx: 23353 rows
✅ Loaded CX2_16_7_23_12.xlsx: 16039 rows
✅ Loaded CX2_16_8_10_12.xlsx: 15625 rows
✅ Loaded CX2_16_8_19_11.xlsx: 22909 rows
✅ Loaded CX2_16_8_1_11.xlsx: 23430 rows
✅ Loaded CX2_16_8_20_12.xlsx: 15127 rows
✅ Loaded CX2_16_8_29_11.xlsx: 22627 rows
✅ Loaded CX2_16_8_30_12.xlsx: 14966 rows
✅ Loaded CX2_16_8_9_11.xlsx: 5894 rows
✅ Loaded CX2_16_9_10_12.xlsx: 14679 rows
✅ Loaded CX2_16_9_16_11.xlsx: 22294 rows
✅ Loaded CX2_16_9_20_11.xlsx: 10096 rows
✅ Loaded CX2_16_9_6_11.xlsx: 1526 rows
✅ Loaded CX2_16_10_14_11.xlsx: 21540 rows
✅ Loaded CX2_16_10_18_11.xlsx: 2896 rows
✅ Loaded CX2_16_10_28_11.xlsx: 16643 rows
✅ Loaded CX2_16_10_4_11.xlsx: 24584 rows
✅ Loaded CX2_16_12_16_11.xlsx: 20456 rows
✅ Loaded CX2_16_1_30_12.xlsx: 17519 rows
✅ Loaded CX2_16_2_13_12_self discharge test.xlsx: 235 rows
✅ Loaded CX2_16_2_15_11.xlsx: 27388 rows
✅ Loaded CX2_16_2_25_11.xlsx: 23669 rows
✅ Loaded CX2_16_2_6_12.xlsx: 517 rows
✅ Loaded CX2_16_3_19_12.xlsx: 17371 rows
✅ Loaded CX2_16_3_21_11.xlsx: 24689 rows
✅ Loaded CX2_16_3_27_12.xlsx: 5905 rows
✅ Loaded CX2_16_3_2_12.xlsx: 17466 rows
✅ Loaded CX2_16_3_7_11.xlsx: 24379 rows
✅ Loaded CX2_16_4_17_12.xlsx: 17484 rows
✅ Loaded CX2_16_4_18_11.xlsx: 5635 rows
✅ Loaded CX2_16_4_1_11.xlsx: 24443 rows
✅ Loaded CX2_16_4_23_12.xlsx: 6390 rows
✅ Loaded CX2_16_4_29_11.xlsx: 23773 rows
✅ Loaded CX2_16_4_5_12.xlsx: 17450 rows
✅ Loaded CX2_16_5_07_12.xlsx: 17063 rows
✅ Loaded CX2_16_5_13_11.xlsx: 8026 rows
✅ Loaded CX2_16_5_16_12.xlsx: 17263 rows
✅ Loaded CX2_16_5_22_12.xlsx: 17353 rows
✅ Loaded CX2_16_5_23_11.xlsx: 23188 rows
✅ Loaded CX2_16_5_9_11.xlsx: 23634 rows
✅ Loaded CX2_16_6_01_12.xlsx: 16964 rows
✅ Loaded CX2_16_6_10_11.xlsx: 2425 rows
✅ Loaded CX2_16_6_13_11.xlsx: 7191 rows
✅ Loaded CX2_16_6_19_12.xlsx: 16746 rows

============================================================
Total rows combined: 820996
Columns: ['Data_Point', 'Test_Time(s)', 'Date_Time', 'Step_Time(s)', 'Step_Index', 'Cycle_Index', 'Current(A)', 'Voltage(V)', 'Charge_Capacity(Ah)', 'Discharge_Capacity(Ah)', 'Charge_Energy(Wh)', 'Discharge_Energy(Wh)', 'dV/dt(V/s)', 'Internal_Resistance(Ohm)', 'Is_FC_Data', 'AC_Impedance(Ohm)', 'ACI_Phase_Angle(Deg)', 'source_file', 'battery_id']

In [8]:
calce_path = Path("../../data/raw/calce")
battery_path = calce_path / "CX2_16"

print("=" * 60)
print("LOADING ALL CX2_16 FILES")
print("=" * 60)

all_files = list(battery_path.glob("*.xlsx"))
all_dfs = []

for file in all_files:
    try:
        xl = pd.ExcelFile(file)
        # Find the sheet that contains cycle data (has 'Channel' in name)
        sheet = [s for s in xl.sheet_names if 'Channel' in s][0]
        df = pd.read_excel(file, sheet_name=sheet)
        df['source_file'] = file.name
        df['battery_id'] = 'CX2_16'
        all_dfs.append(df)
        print(f"✅ Loaded: {file.name} - {len(df)} rows")
    except Exception as e:
        print(f"❌ Failed: {file.name} - {e}")

# Combine all dataframes
combined = pd.concat(all_dfs, ignore_index=True)

print(f"\n✅ Total rows loaded: {len(combined):,}")
print(f"✅ Columns: {list(combined.columns)[:10]}...")

============================================================
LOADING ALL CX2_16 FILES
============================================================
✅ Loaded: CX2_16_4_12_11.xlsx - 24195 rows
✅ Loaded: CX2_16_6_20_11.xlsx - 16615 rows
✅ Loaded: CX2_16_6_28_12.xlsx - 2849 rows
✅ Loaded: CX2_16_6_30_11.xlsx - 23433 rows
✅ Loaded: CX2_16_6_7_11.xlsx - 15780 rows
✅ Loaded: CX2_16_7_03_12.xlsx - 16704 rows
✅ Loaded: CX2_16_7_11_11.xlsx - 6227 rows
✅ Loaded: CX2_16_7_12_12.xlsx - 16343 rows
✅ Loaded: CX2_16_7_21_11.xlsx - 23353 rows
✅ Loaded: CX2_16_7_23_12.xlsx - 16039 rows
✅ Loaded: CX2_16_8_10_12.xlsx - 15625 rows
✅ Loaded: CX2_16_8_19_11.xlsx - 22909 rows
✅ Loaded: CX2_16_8_1_11.xlsx - 23430 rows
✅ Loaded: CX2_16_8_20_12.xlsx - 15127 rows
✅ Loaded: CX2_16_8_29_11.xlsx - 22627 rows
✅ Loaded: CX2_16_8_30_12.xlsx - 14966 rows
✅ Loaded: CX2_16_8_9_11.xlsx - 5894 rows
✅ Loaded: CX2_16_9_10_12.xlsx - 14679 rows
✅ Loaded: CX2_16_9_16_11.xlsx - 22294 rows
✅ Loaded: CX2_16_9_20_11.xlsx - 10096 rows
✅ Loaded: CX2_16_9_6_11.xlsx - 1526 rows
✅ Loaded: CX2_16_10_14_11.xlsx - 21540 rows
✅ Loaded: CX2_16_10_18_11.xlsx - 2896 rows
✅ Loaded: CX2_16_10_28_11.xlsx - 16643 rows
✅ Loaded: CX2_16_10_4_11.xlsx - 24584 rows
✅ Loaded: CX2_16_12_16_11.xlsx - 20456 rows
✅ Loaded: CX2_16_1_30_12.xlsx - 17519 rows
✅ Loaded: CX2_16_2_13_12_self discharge test.xlsx - 235 rows
✅ Loaded: CX2_16_2_15_11.xlsx - 27388 rows
✅ Loaded: CX2_16_2_25_11.xlsx - 23669 rows
✅ Loaded: CX2_16_2_6_12.xlsx - 517 rows
✅ Loaded: CX2_16_3_19_12.xlsx - 17371 rows
✅ Loaded: CX2_16_3_21_11.xlsx - 24689 rows
✅ Loaded: CX2_16_3_27_12.xlsx - 5905 rows
✅ Loaded: CX2_16_3_2_12.xlsx - 17466 rows
✅ Loaded: CX2_16_3_7_11.xlsx - 24379 rows
✅ Loaded: CX2_16_4_17_12.xlsx - 17484 rows
✅ Loaded: CX2_16_4_18_11.xlsx - 5635 rows
✅ Loaded: CX2_16_4_1_11.xlsx - 24443 rows
✅ Loaded: CX2_16_4_23_12.xlsx - 6390 rows
✅ Loaded: CX2_16_4_29_11.xlsx - 23773 rows
✅ Loaded: CX2_16_4_5_12.xlsx - 17450 rows
✅ Loaded: CX2_16_5_07_12.xlsx - 17063 rows
✅ Loaded: CX2_16_5_13_11.xlsx - 8026 rows
✅ Loaded: CX2_16_5_16_12.xlsx - 17263 rows
✅ Loaded: CX2_16_5_22_12.xlsx - 17353 rows
✅ Loaded: CX2_16_5_23_11.xlsx - 23188 rows
✅ Loaded: CX2_16_5_9_11.xlsx - 23634 rows
✅ Loaded: CX2_16_6_01_12.xlsx - 16964 rows
✅ Loaded: CX2_16_6_10_11.xlsx - 2425 rows
✅ Loaded: CX2_16_6_13_11.xlsx - 7191 rows
✅ Loaded: CX2_16_6_19_12.xlsx - 16746 rows

✅ Total rows loaded: 820,996
✅ Columns: ['Data_Point', 'Test_Time(s)', 'Date_Time', 'Step_Time(s)', 'Step_Index', 'Cycle_Index', 'Current(A)', 'Voltage(V)', 'Charge_Capacity(Ah)', 'Discharge_Capacity(Ah)']...

In [10]:
print("=" * 60)
print("AGGREGATING CX2_16 DATA TO CYCLE LEVEL")
print("=" * 60)

# Aggregate by source_file and Cycle_Index
cycle_summary = combined.groupby(['source_file', 'Cycle_Index']).agg({
    # Current features
    'Current(A)': ['mean', 'max', 'min', 'std'],
    
    # Voltage features
    'Voltage(V)': ['mean', 'max', 'min', 'std'],
    
    # Capacity features
    'Charge_Capacity(Ah)': 'max',
    'Discharge_Capacity(Ah)': 'max',
    
    # Energy features
    'Charge_Energy(Wh)': 'max',
    'Discharge_Energy(Wh)': 'max',
    
    # Internal resistance
    'Internal_Resistance(Ohm)': ['mean', 'max'],
    
    # Time duration of the cycle
    'Test_Time(s)': 'max'
}).round(4)

# Flatten column names
cycle_summary.columns = [
    'current_mean_A', 'current_max_A', 'current_min_A', 'current_std_A',
    'voltage_mean_V', 'voltage_max_V', 'voltage_min_V', 'voltage_std_V',
    'charge_capacity_Ah', 'discharge_capacity_Ah',
    'charge_energy_Wh', 'discharge_energy_Wh',
    'resistance_mean_ohm', 'resistance_max_ohm',
    'duration_seconds'
]

# Reset index to make source_file and Cycle_Index regular columns
cycle_summary = cycle_summary.reset_index()

# Add battery_id
cycle_summary['battery_id'] = 'CX2_16'

# Rename Cycle_Index to cycle_number for consistency
cycle_summary = cycle_summary.rename(columns={'Cycle_Index': 'cycle_number'})

# Calculate State of Health (SOH) - actual percentage, not label
max_capacity = cycle_summary['discharge_capacity_Ah'].max()
cycle_summary['soh_percent'] = (cycle_summary['discharge_capacity_Ah'] / max_capacity) * 100
cycle_summary['soh_percent'] = cycle_summary['soh_percent'].clip(0, 100)

print(f"\n✅ Aggregation complete!")
print(f"   Original per-second rows: {len(combined):,}")
print(f"   Aggregated cycle rows: {len(cycle_summary):,}")

print("\n📊 Preview of aggregated data:")
cycle_summary.head(10)

============================================================
AGGREGATING CX2_16 DATA TO CYCLE LEVEL
============================================================

✅ Aggregation complete!
   Original per-second rows: 820,996
   Aggregated cycle rows: 2,018

📊 Preview of aggregated data:

,source_file,cycle_number,current_mean_A,current_max_A,current_min_A,current_std_A,voltage_mean_V,voltage_max_V,voltage_min_V,voltage_std_V,charge_capacity_Ah,discharge_capacity_Ah,charge_energy_Wh,discharge_energy_Wh,resistance_mean_ohm,resistance_max_ohm,duration_seconds,battery_id,soh_percent
0,CX2_16_10_14_11.xlsx,1,-0.0439,1.1975,-0.5505,0.5970,3.8297,4.2004,2.6999,0.2687,1.0633,1.0808,4.3020,3.9920,0.0532,0.0925,16605.3056,CX2_16,1.613585
1,CX2_16_10_14_11.xlsx,2,-0.0284,1.2058,-0.5507,0.5996,3.8246,4.2004,2.6999,0.2667,2.1605,2.1768,8.7128,8.0434,0.0839,0.0924,32837.3901,CX2_16,3.249862
2,CX2_16_10_14_11.xlsx,3,-0.0273,1.1993,-0.5505,0.6002,3.8233,4.2002,2.6999,0.2685,3.2703,3.2875,13.1662,12.1566,0.0836,0.0915,49046.4243,CX2_16,4.908086
3,CX2_16_10_14_11.xlsx,4,-0.0214,1.1908,-0.5505,0.6005,3.8207,4.2002,2.6999,0.2689,4.3791,4.3830,17.6106,16.2044,0.0822,0.0902,65060.1454,CX2_16,6.543617
4,CX2_16_10_14_11.xlsx,5,-0.0256,1.2065,-0.5505,0.6000,3.8238,4.2004,2.6999,0.2693,5.4725,5.4747,22.0033,20.2373,0.0830,0.0909,81014.2951,CX2_16,8.173475
5,CX2_16_10_14_11.xlsx,6,-0.0253,1.2121,-0.5507,0.6003,3.8239,4.2004,2.6999,0.2704,6.5635,6.5659,26.3870,24.2686,0.0838,0.0917,96949.7975,CX2_16,9.802587
6,CX2_16_10_14_11.xlsx,7,-0.0271,1.2086,-0.5505,0.5999,3.8215,4.2002,2.6999,0.2715,7.6521,7.6569,30.7604,28.2966,0.0843,0.0925,112853.7024,CX2_16,11.431400
7,CX2_16_10_14_11.xlsx,8,-0.0288,1.2059,-0.5505,0.5996,3.8252,4.2001,2.6999,0.2693,8.7487,8.7644,35.1634,32.3973,0.0834,0.0908,128890.5641,CX2_16,13.084846
8,CX2_16_10_14_11.xlsx,9,-0.0208,1.1946,-0.5505,0.6009,3.8239,4.2001,2.6999,0.2694,9.8583,9.8638,39.6112,36.4663,0.0826,0.0908,144899.6452,CX2_16,14.726200
9,CX2_16_10_14_11.xlsx,10,-0.0236,1.2266,-0.5505,0.6014,3.8218,4.2004,2.6999,0.2724,10.9455,10.9460,43.9789,40.4603,0.0849,0.0932,160748.2148,CX2_16,16.341875

In [12]:

# Save to Excel
output_path = Path("../../data/processed/calce/CX2_16_cycle_level.xlsx")
cycle_summary.to_excel(output_path, index=False)
print(f"\n✅ Saved to: {output_path}")

# Also save as CSV
csv_path = Path("../../data/processed/calce/CX2_16_cycle_level.csv")
cycle_summary.to_csv(csv_path, index=False)
print(f"✅ Also saved as CSV: {csv_path}")

# Quick stats
print("\n📊 SOH Statistics:")
print(f"   Min SOH: {cycle_summary['soh_percent'].min():.1f}%")
print(f"   Max SOH: {cycle_summary['soh_percent'].max():.1f}%")
print(f"   Mean SOH: {cycle_summary['soh_percent'].mean():.1f}%")

✅ Saved to: ../../data/processed/calce/CX2_16_cycle_level.xlsx
✅ Also saved as CSV: ../../data/processed/calce/CX2_16_cycle_level.csv

📊 SOH Statistics:
   Min SOH: 0.0%
   Max SOH: 100.0%
   Mean SOH: 38.0%